# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import carbon_service_pb2 as carbon__service__pb2


class CarbonServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProjects = channel.unary_unary(
                '/carbon.CarbonService/GetProjects',
                request_serializer=carbon__service__pb2.ProjectQuery.SerializeToString,
                response_deserializer=carbon__service__pb2.ProjectResponse.FromString,
                )
        self.GetNews = channel.unary_unary(
                '/carbon.CarbonService/GetNews',
                request_serializer=carbon__service__pb2.NewsQuery.SerializeToString,
                response_deserializer=carbon__service__pb2.NewsResponse.FromString,
                )
        self.GetFinanceData = channel.unary_unary(
                '/carbon.CarbonService/GetFinanceData',
                request_serializer=carbon__service__pb2.FinanceQuery.SerializeToString,
                response_deserializer=carbon__service__pb2.FinanceResponse.FromString,
                )
        self.GetProjectDetail = channel.unary_unary(
                '/carbon.CarbonService/GetProjectDetail',
                request_serializer=carbon__service__pb2.ProjectDetailQuery.SerializeToString,
                response_deserializer=carbon__service__pb2.ProjectDetailResponse.FromString,
                )


class CarbonServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFinanceData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarbonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjects,
                    request_deserializer=carbon__service__pb2.ProjectQuery.FromString,
                    response_serializer=carbon__service__pb2.ProjectResponse.SerializeToString,
            ),
            'GetNews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNews,
                    request_deserializer=carbon__service__pb2.NewsQuery.FromString,
                    response_serializer=carbon__service__pb2.NewsResponse.SerializeToString,
            ),
            'GetFinanceData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFinanceData,
                    request_deserializer=carbon__service__pb2.FinanceQuery.FromString,
                    response_serializer=carbon__service__pb2.FinanceResponse.SerializeToString,
            ),
            'GetProjectDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectDetail,
                    request_deserializer=carbon__service__pb2.ProjectDetailQuery.FromString,
                    response_serializer=carbon__service__pb2.ProjectDetailResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'carbon.CarbonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CarbonService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/carbon.CarbonService/GetProjects',
            carbon__service__pb2.ProjectQuery.SerializeToString,
            carbon__service__pb2.ProjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/carbon.CarbonService/GetNews',
            carbon__service__pb2.NewsQuery.SerializeToString,
            carbon__service__pb2.NewsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFinanceData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/carbon.CarbonService/GetFinanceData',
            carbon__service__pb2.FinanceQuery.SerializeToString,
            carbon__service__pb2.FinanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProjectDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/carbon.CarbonService/GetProjectDetail',
            carbon__service__pb2.ProjectDetailQuery.SerializeToString,
            carbon__service__pb2.ProjectDetailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
